repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0  # Use the latest version of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the latest version of Black
    hooks:
      - id: black
        language_version: python3  # Specify the Python version for Black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the latest version of isort
    hooks:
      - id: isort
        args: ["--profile", "black"]  # Make isort compatible with Black
